version: '3'

services:

  ss-server:
    container_name: ss-server
    command: "-k ${SS_PASSWORD}"
    image: wendellsun/ss-server
    ports:
      - "3389:3389"
    restart: always

  ss-client:
    container_name: ss-client
    command: "-s ss-server -p 3389 -k ${SS_PASSWORD}"
    image: wendellsun/ss-client
    restart: always

  polipo:
    container_name: polipo
    image: vimagick/polipo
    command:
      - "authCredentials=${HTTP_USERNAME}:${HTTP_PASSWORD}"
      - "socksParentProxy=ss-client:1030"
    ports:
      - "8123:8123"
    restart: always
