version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  gogs:
    container_name: gogs
    image: gogs/gogs
    volumes:
      - "./data:/data"
    ports:
      - "3000:3000"
      - "22:22"
    restart: always
