version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gogs

  gogs:
    container_name: gogs
    image: gogs/gogs
    depends_on:
      - mysql
    volumes:
      - "./gogs:/data"
    environment:
      - VIRTUAL_HOST=git.sunwen.in
      - VIRTUAL_PORT=3000
    links:
      - mysql
    ports:
      - "3000:3000"
      - "22:22"
    restart: always
