version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./certs:/etc/nginx/certs:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    restart: always

  nginx-proxy-ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-ssl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/etc/nginx/certs:rw"
    volumes_from:
      - "nginx-proxy"
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wendellsun
      MYSQL_DATABASE: gogs

  gogs:
    container_name: gogs
    image: gogs/gogs
    depends_on:
      - mysql
    volumes:
      - "./gogs-data:/data"
    environment:
      - "VIRTUAL_HOST=git.sunwen.in"
      - "VIRTUAL_PORT=3000"
      - "LETSENCRYPT_HOST=git.sunwen.in"
      - "LETSENCRYPT_EMAIL=iwendellsun@gmail.com"
    links:
      - mysql
    ports:
      - "3000:3000"
      - "22:22"
    restart: always
